### ISSUE TITLE
Bidmanager API v1 will get deprecated by April 15th - are there plans to update Argon?

### ISSUE THREAD

**Issue by mfr-edialog** [google/argon#7] opened 2021-03-23 18:10 UTC
Hi there,

As Argon is currently still using V1 of the API which will be replaced by 1.1. on April 15th 2021, will Argon get updated?
Please see the message we received below.

Thank you! :)

------

As previously announced, we will be sunsetting these deprecated services of the API on April 15, 2021. Requests to these services will no longer work after this date. To avoid an interruption in service, you must migrate to either a newer version of the DBM API or the Display & Video 360 (DV360) API, depending on the services you currently use.
--
If you are using the DBM API version 1 Reporting service, you must migrate to the DBM API version 1.1 Reporting service. If you are using any version of the DBM API SDF Download or Line Item service, you must migrate to the DV360 API.
To learn about changes between versions and get tips for migrating, visit the API developer site and read the Google Ads Developer Blog post about this upcoming sunset. Also consider subscribing to the Developer Blog to stay up to date about new releases, upcoming sunsets, and changes to the DBM API or DV360 API.
If you have technical questions regarding new versions of the API, please reach out via the support contact form.
Sincerely,
The DoubleClick Bid Manager API Team

**Comment by dnnspaul** [comment] 2021-03-24 10:12
~I have fixed the problem in https://github.com/dnnspaul/argon but can't submit a pull request...~

PR: https://github.com/google/argon/pull/8

**Comment by achembarpu** [comment] 2021-03-24 11:13
Hi all,

Thanks for reaching out on this topic. We are aiming to release a new version of Argon soon. This will cover both the API version, and other API-related changes that are coming up in April. Thank you for your patience, and we will keep you posted.

Cheers,
Arvind

**Comment by achembarpu** [comment] 2021-03-29 14:51
Hi everyone,

We have a new release out on the new default `main` branch, as v3.3.0. This addresses:
- CM & DV API versions update
- CM360/DV360 field renames
- Various dependencies updated

Do give us feedback once you are able to deploy this new version. Thanks!

Cheers,
Arvind

**Comment by mfr-edialog** [comment] 2021-04-09 12:30
We were able to deploy the new function perfectly fine.
There seems to be an issue with the new API version with the DV connector (we cannot retrieve any data from DV to BQ with Argon 3.30). After investigating this in more detail checking the logs we tried the API playground on https://developers.google.com/bid-manager/v1.1/reports/listreports and saw that it throws an unspecific error message as where with the old V1 version it works just fine.

We will raise the issue with the API team as Argon itself does not seem to be the issue but rather the API itself.

**Comment by mfr-edialog** [comment] 2021-04-22 16:43
After checking with API support it seems that the API is working fine. Did you test if DV360 reports are working with 3.30 on your end? We are currently stuck with no data incoming from DV360.

**Comment by mfr-edialog** [comment] 2021-04-26 15:27
Hi again @achembarpu ,

We investigated in more detail and assume the following:

In version 1 DV360 reports and files could be requested through the getquery method.
In version 1.1 DV360 reports need to be requested via the listreports method and files through the getquery method.
But it seems that the new argon version still requests DV360 reports via the getquery method.

Can you confirm this? We are happy to supply further information on the errors we see with the current version of argon for the DV360 reports.

**Comment by achembarpu** [comment] 2021-04-28 14:11
Hi @mfr-edialog ,

Thanks for providing your feedback on this update, much appreciated!

> DV360 reports need to be requested via the listreports method and files through the getquery method.

Argon has always used [listreports](https://developers.google.com/bid-manager/v1.1/reports/listreports) to fetch authenticated links to the actual files [[src code](https://github.com/google/argon/blob/main/dv.js#L76)]. My local installation of Argon is able to successfully download files, so I am unable to replicate the problem.

Could you upload logs showing the errors that you are facing? Thanks!

**Comment by mfr-edialog** [comment] 2021-04-28 15:59
Thank you for looking into this, I attached the log as CSV. I created a fresh report, but the errors messages are the same for the existing one. I obfuscated any possible keys with "XYZ"

[Argon_DV360_error_log.csv](https://github.com/google/argon/files/6393217/Argon_DV360_error_log.csv)

**Comment by mfr-edialog** [comment] 2021-04-29 08:31
Another finding I can share: I made a test today with version 3.2.1 of Argon using DV360 where I only changed 'https://www.googleapis.com/doubleclickbidmanager/v1'; -> 'https://www.googleapis.com/doubleclickbidmanager/v1.1';.
and it successfully ingested the data.

**Comment by achembarpu** [comment] 2021-04-29 14:57
Thanks for the update on this. I have investigated this further, since the logs imply an authentication issue. The regression occurs due to changes in `google-auth-library`. We are looking into this, but there is no timeline for resolution. In the meanwhile, you can downgrade the dependency to `5.1.2` to mitigate the error.

**Comment by MariusFall** [comment] 2021-04-29 17:18
Hello,
Same problem here but the DV data ingestion stopped today. I've tried downgrading the `google-auth-library` to `5.1.2` with the last version of Argon with no success.
I will try the solution proposed by mfr-edialog

**Comment by MariusFall** [comment] 2021-04-29 20:01
changing the 'https://www.googleapis.com/doubleclickbidmanager/v1'; to 'https://www.googleapis.com/doubleclickbidmanager/v1.1'; also worked for me.
Thanks :)

**Comment by achembarpu** [comment] 2021-04-30 11:16
Hi all, We have released a new version `3.3.1` which should resolve the issues being discussed here. Do update and let us know your feedback. Thanks!

**Comment by MariusFall** [comment] 2021-04-30 15:27
Hi @achembarpu ! just tested the `3.3.1` version and it works like a charm for me :) 
Thanks for the fix and your reactivity !

**Comment by achembarpu** [comment] 2021-05-03 10:26
Glad to hear it's working now! I'll close this now, but if anyone else is facing issues, do re-open with logs. Thanks!

**Closed as completed by achembarpu** 2021-05-03 10:26 UTC
